# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'

workspace 'AzureIoTServiceSampleWorkspace'

target 'AzureIoTServiceSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AzureIoTServiceSample
  pod 'AzureIoTUtility'
  pod 'AzureIoTuAmqp'
  pod 'AzureIoTHubServiceClient', '0.0.1-preview01'
end