# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'

workspace 'MQTT Client Sample'

target 'MQTT Client Sample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MQTT Client Sample
  pod 'AzureIoTUtility', '=1.1.12d'
  pod 'AzureIoTuMqtt', '=1.1.12d'
  pod 'AzureIoTuAmqp', '=1.2.12d'
  pod 'AzureIoTHubClient', '=1.3.6-nightly-a'
end
